places=["America", "Japan" , "Hawai", "Korea", "England"]
print("Original places:")
print(places)
print("\nAlphabetically correct:")
print(sorted(places))
print("\nOriginal places:")
print(places)
print("\nReverse alphabetical")
print(sorted(places, reverse=True))
print("\nOriginal places:")
print("Original places:")
print(places)
print("\nReversed:")
places.reverse()
print(places)
print("\nOriginal order:")
places.reverse()
print(places)
print("\nAlphabetically correct:")
places.sort()
print(places)
print("\nReverse alphabetical")
places.sort()
print(places)