guests= ["Abril","Angela", "Rence"]
name=guests[0].title()
print(f"{name}, thanks for confirming the invitation")
name=guests[1].title()
print(f"{name}, thanks for confiriming the invitation")
name=guests[2].title()
print(f"{name}, thanks for confirming the invitation")
name=guests[0].title()
print(f"\nSorry but {name} canceled her invitation")
#Abril canceled her invitation so lets invite someone else
del(guests[0])
guests.insert(0, "Hannah")
#Resend the invitation again
name=guests[0].title()
print(f"\n{name}, thanks for confirming the invitation")
name=guests[1].title()
print(f"{name}, thanks for confirming the invitation")
name=guests[2].title()
print(f"{name}, thanks for confirming the invitation")
#A lot of people canceled their invitation, lets invite more
print("\nWe have more space now!")
guests.insert(0, "Keira")
guests.insert(2, "Jun")
guests.append("Slick")
name= guests[0].title()
print(f"{name}, thanks for confirming the invitation")
name=guests[1].title()
print(f"{name}, thanks for confirming the invitation")
name=guests[2].title()
print(f"{name}, thanks for confirming the invitation")
name=guests[3].title()
print(f"{name}, thanks for confirming the invitation")
name=guests[4].title()
print(f"{name}, thanks for confirming the invitation")
name=guests[5].title()
print(f"{name}, thanks for confirming the invitation")
#More people arrived 
print("\nSorry, but more people arrived so you have to cancel your invitation")
name=guests.pop()
print(f"Sorry, {name.title()} there's more people")
name=guests.pop()
print(f"Sorry, {name.title()} there's more people")
name=guests.pop()
print(f"Sorry, {name.title()} there's more people")
name=guests.pop()
print(f"Sorry, {name.title()} there's more people")
#There are two people remaining. Lets send an invitation
name=guests[0].title()
print(f"{name}, thanks for confirming the invitation")
name=guests[1].title()
print(f"{name}, thanks for confirming the invitation")
#Empty all the lists 
del(guests[0])
del(guests[0])
#Check if the list is empty
print(guests)